<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitab7e171a0b7d4c84f78a7e334ec28d7b
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitab7e171a0b7d4c84f78a7e334ec28d7b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitab7e171a0b7d4c84f78a7e334ec28d7b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
